#include "Maps_Txt.h"

#include "platform_io.h"
#include "txt_parse_helpers.h"

#include <algorithm>
#include <cstdio>
#include <cstdlib>
#include <cstring>

// Set default values for a map_entry (called right after memset to 0).
static void set_map_defaults(map_entry* m) {
    m->dead_bodies_age = true;
    m->can_rest_here[0] = true;
    m->can_rest_here[1] = true;
    m->can_rest_here[2] = true;
    m->pipboy_active = true;
}

// Parse comma-separated "name:weight" pairs into ambient_sfx array.
static void parse_ambient_sfx(const char* val, map_entry* m) {
    m->ambient_sfx_count = 0;
    while (*val != '\0' && m->ambient_sfx_count < MAX_AMBIENT_SFX) {
        // Skip whitespace
        while (*val == ' ' || *val == '\t') {
            val++;
        }
        if (*val == '\0') {
            break;
        }

        // Find colon separator
        const char* colon = strchr(val, ':');
        if (colon == nullptr) {
            break;
        }

        ambient_sfx_entry* sfx = &m->ambient_sfx[m->ambient_sfx_count];
        int name_len = (int)(colon - val);
        if (name_len >= (int)sizeof(sfx->name)) {
            name_len = (int)sizeof(sfx->name) - 1;
        }
        memcpy(sfx->name, val, name_len);
        sfx->name[name_len] = '\0';

        // Trim trailing whitespace from name
        int nlen = name_len;
        while (nlen > 0 && (sfx->name[nlen - 1] == ' ' || sfx->name[nlen - 1] == '\t')) {
            sfx->name[--nlen] = '\0';
        }

        sfx->weight = atoi(colon + 1);
        m->ambient_sfx_count++;

        // Advance past this entry
        const char* comma = strchr(colon, ',');
        if (comma != nullptr) {
            val = comma + 1;
        } else {
            break;
        }
    }
}

// Parse "can_rest_here" — either a single Yes/No or three comma-separated values.
static void parse_can_rest_here(const char* val, map_entry* m) {
    while (*val == ' ' || *val == '\t') {
        val++;
    }

    // Check for comma — if present, parse three values
    const char* c1 = strchr(val, ',');
    if (c1 != nullptr) {
        m->can_rest_here[0] = parse_yes_no(val);
        const char* c2 = strchr(c1 + 1, ',');
        if (c2 != nullptr) {
            m->can_rest_here[1] = parse_yes_no(c1 + 1);
            m->can_rest_here[2] = parse_yes_no(c2 + 1);
        } else {
            m->can_rest_here[1] = parse_yes_no(c1 + 1);
            m->can_rest_here[2] = m->can_rest_here[1];
        }
    } else {
        // Single value applies to all three
        bool v = parse_yes_no(val);
        m->can_rest_here[0] = v;
        m->can_rest_here[1] = v;
        m->can_rest_here[2] = v;
    }
}

// Parse "random_start_point_N" — format: "elev:X, tile_num:Y"
static void parse_random_start(const char* key, const char* val, map_entry* m) {
    // Extract N from "random_start_point_N"
    const char* underscore = key + strlen("random_start_point_");
    int idx = atoi(underscore);
    if (idx < 0 || idx >= MAX_RANDOM_STARTS) {
        return;
    }

    random_start_point* rsp = &m->random_starts[idx];

    // Parse "elev:X, tile_num:Y"
    const char* elev_colon = strstr(val, "elev:");
    if (elev_colon != nullptr) {
        rsp->elevation = atoi(elev_colon + 5);
    }

    const char* tile_colon = strstr(val, "tile_num:");
    if (tile_colon != nullptr) {
        rsp->tile_num = atoi(tile_colon + 9);
    }

    if (idx >= m->random_start_count) {
        m->random_start_count = idx + 1;
    }
}

// --- write ---

bool write_maps_txt(const char* path, maps_txt_data* data) {
    if (path == nullptr || data == nullptr) {
        return false;
    }

    char txt_path[MAX_PATH];
    snprintf(txt_path, MAX_PATH, "%s/maps.txt", path);

    FILE* file = fopen(txt_path, "w");
    if (file == nullptr) {
        printf("Error: write_maps_txt(), unable to open %s for writing: L%d\n", txt_path, __LINE__);
        return false;
    }

    fprintf(file, "; Generated by FO2MapEdit\n\n");

    for (int i = 0; i < data->map_count; i++) {
        map_entry* m = &data->maps[i];

        fprintf(file, "[Map %03d]\n", m->map_number);
        fprintf(file, "lookup_name=%s\n", m->lookup_name);
        fprintf(file, "map_name=%s\n", m->map_name);

        if (m->music[0] != '\0') {
            fprintf(file, "music=%s\n", m->music);
        }

        if (m->ambient_sfx_count > 0) {
            fprintf(file, "ambient_sfx=");
            for (int j = 0; j < m->ambient_sfx_count; j++) {
                if (j > 0) {
                    fprintf(file, ", ");
                }
                fprintf(file, "%s:%d", m->ambient_sfx[j].name, m->ambient_sfx[j].weight);
            }
            fprintf(file, "\n");
        }

        fprintf(file, "saved=%s\n", m->saved ? "Yes" : "No");
        if (!m->dead_bodies_age) {
            fprintf(file, "dead_bodies_age=No\n");
        }
        if (!m->can_rest_here[0] || !m->can_rest_here[1] || !m->can_rest_here[2]) {
            fprintf(file, "can_rest_here=%s,%s,%s\n", m->can_rest_here[0] ? "Yes" : "No",
                    m->can_rest_here[1] ? "Yes" : "No", m->can_rest_here[2] ? "Yes" : "No");
        }
        if (!m->pipboy_active) {
            fprintf(file, "pipboy_active=No\n");
        }

        if (m->state_on) {
            fprintf(file, "state=On\n");
        }

        for (int j = 0; j < m->random_start_count; j++) {
            fprintf(file, "random_start_point_%d=elev:%d, tile_num:%d\n", j,
                    m->random_starts[j].elevation, m->random_starts[j].tile_num);
        }

        fprintf(file, "\n");
    }

    fclose(file);
    printf("write_maps_txt(): wrote %d maps to %s\n", data->map_count, txt_path);
    return true;
}

// --- public API ---

maps_txt_data* parse_maps_txt_from_buffer(char* txt) {
    maps_txt_data* data = (maps_txt_data*)calloc(1, sizeof(maps_txt_data));
    if (data == nullptr) {
        return nullptr;
    }

    if (txt == nullptr || *txt == '\0') {
        return data;
    }

    map_entry* current = nullptr;

    char* line = txt;
    while (line != nullptr && *line != '\0') {
        char* eol = strchr(line, '\n');
        int line_len = (eol != nullptr) ? (int)(eol - line) : (int)strlen(line);

        // Make null-terminated copy
        char buf[512];
        int copy_len = (line_len < (int)sizeof(buf) - 1) ? line_len : (int)sizeof(buf) - 1;
        memcpy(buf, line, copy_len);
        buf[copy_len] = '\0';
        trim_trailing(buf);

        // Skip comments and empty lines
        if (buf[0] == ';' || buf[0] == '\0') {
            line = (eol != nullptr) ? eol + 1 : nullptr;
            continue;
        }

        // Check for [Map NNN] section header
        int map_num = -1;
        if (sscanf(buf, "[Map %d]", &map_num) == 1) {
            if (data->map_count >= MAX_MAP_ENTRIES) {
                printf("Warning: parse_maps_txt(), max map entries reached (%d)\n",
                       MAX_MAP_ENTRIES);
                line = (eol != nullptr) ? eol + 1 : nullptr;
                continue;
            }
            current = &data->maps[data->map_count];
            memset(current, 0, sizeof(map_entry));
            set_map_defaults(current);
            current->map_number = map_num;
            data->map_count++;
            line = (eol != nullptr) ? eol + 1 : nullptr;
            continue;
        }

        if (current == nullptr) {
            line = (eol != nullptr) ? eol + 1 : nullptr;
            continue;
        }

        // Strip inline comments (;)
        char* comment = strchr(buf, ';');
        if (comment != nullptr) {
            *comment = '\0';
            trim_trailing(buf);
        }

        // Parse key=value
        char* eq = strchr(buf, '=');
        if (eq == nullptr) {
            line = (eol != nullptr) ? eol + 1 : nullptr;
            continue;
        }

        *eq = '\0';
        char* key = buf;
        char* val = eq + 1;
        // Trim key
        trim_trailing(key);
        while (*key == ' ' || *key == '\t') {
            key++;
        }

        if (strcasecmp(key, "lookup_name") == 0) {
            while (*val == ' ' || *val == '\t') {
                val++;
            }
            strncpy(current->lookup_name, val, MAP_NAME_LEN - 1);
            current->lookup_name[MAP_NAME_LEN - 1] = '\0';
        } else if (strcasecmp(key, "map_name") == 0) {
            while (*val == ' ' || *val == '\t') {
                val++;
            }
            strncpy(current->map_name, val, MAP_NAME_LEN - 1);
            current->map_name[MAP_NAME_LEN - 1] = '\0';
        } else if (strcasecmp(key, "music") == 0) {
            while (*val == ' ' || *val == '\t') {
                val++;
            }
            strncpy(current->music, val, MAP_NAME_LEN - 1);
            current->music[MAP_NAME_LEN - 1] = '\0';
        } else if (strcasecmp(key, "ambient_sfx") == 0) {
            parse_ambient_sfx(val, current);
        } else if (strcasecmp(key, "saved") == 0) {
            current->saved = parse_yes_no(val);
        } else if (strcasecmp(key, "dead_bodies_age") == 0) {
            current->dead_bodies_age = parse_yes_no(val);
        } else if (strcasecmp(key, "can_rest_here") == 0) {
            parse_can_rest_here(val, current);
        } else if (strcasecmp(key, "pipboy_active") == 0) {
            current->pipboy_active = parse_yes_no(val);
        } else if (strcasecmp(key, "state") == 0) {
            while (*val == ' ' || *val == '\t') {
                val++;
            }
            current->state_on = (strncasecmp(val, "On", 2) == 0);
        } else if (str_starts_with(key, "random_start_point_")) {
            parse_random_start(key, val, current);
        }

        line = (eol != nullptr) ? eol + 1 : nullptr;
    }

    return data;
}

maps_txt_data* parse_maps_txt(const char* path) {
    char* txt = io_load_txt_file(path);
    if (txt == nullptr) {
        printf("Error: parse_maps_txt(), unable to load: %s\n", path);
        return nullptr;
    }

    auto* data = parse_maps_txt_from_buffer(txt);
    free(txt);

    if (data != nullptr) {
        printf("parse_maps_txt(): parsed %d maps from %s\n", data->map_count, path);
    }
    return data;
}

// --- Serialization ---

// Fixed-size binary format:
// [4B] map_count
// Per map_entry (×MAX_MAP_ENTRIES):
//   [4B map_number][48B lookup_name][48B map_name][48B music]
//   [4B ambient_sfx_count]
//   Per ambient_sfx (×MAX_AMBIENT_SFX):
//     [32B name][4B weight]
//   [1B saved][1B dead_bodies_age][3B can_rest_here][1B pipboy_active][1B state_on]
//   [4B random_start_count]
//   Per random_start (×MAX_RANDOM_STARTS):
//     [4B elevation][4B tile_num]

static constexpr int SFX_SERIAL_SIZE = 32 + 4;         // 36
static constexpr int RANDOM_START_SERIAL_SIZE = 4 + 4; // 8
static constexpr int MAP_ENTRY_SERIAL_SIZE =
    4 + MAP_NAME_LEN + MAP_NAME_LEN + MAP_NAME_LEN + 4 + (MAX_AMBIENT_SFX * SFX_SERIAL_SIZE) + 1 +
    1 + 3 + 1 + 1 + 4 + (MAX_RANDOM_STARTS * RANDOM_START_SERIAL_SIZE); // 603
static constexpr int MAPS_DATA_SERIAL_SIZE =
    4 + (MAX_MAP_ENTRIES * MAP_ENTRY_SERIAL_SIZE); // 120604

uint8_t* serialize_maps_data(maps_txt_data* data, int* out_size) {
    if (data == nullptr || out_size == nullptr) {
        return nullptr;
    }

    *out_size = MAPS_DATA_SERIAL_SIZE;
    uint8_t* buf = (uint8_t*)calloc(1, MAPS_DATA_SERIAL_SIZE);
    if (buf == nullptr) {
        return nullptr;
    }

    uint8_t* p = buf;

    memcpy(p, &data->map_count, 4);
    p += 4;

    for (auto& m : data->maps) {
        map_entry* entry = &m;
        memcpy(p, &entry->map_number, 4);
        p += 4;
        memcpy(p, entry->lookup_name, MAP_NAME_LEN);
        p += MAP_NAME_LEN;
        memcpy(p, entry->map_name, MAP_NAME_LEN);
        p += MAP_NAME_LEN;
        memcpy(p, entry->music, MAP_NAME_LEN);
        p += MAP_NAME_LEN;

        memcpy(p, &entry->ambient_sfx_count, 4);
        p += 4;
        for (auto& sfx : entry->ambient_sfx) {
            memcpy(p, sfx.name, 32);
            p += 32;
            memcpy(p, &sfx.weight, 4);
            p += 4;
        }

        *p++ = entry->saved ? 1 : 0;
        *p++ = entry->dead_bodies_age ? 1 : 0;
        *p++ = entry->can_rest_here[0] ? 1 : 0;
        *p++ = entry->can_rest_here[1] ? 1 : 0;
        *p++ = entry->can_rest_here[2] ? 1 : 0;
        *p++ = entry->pipboy_active ? 1 : 0;
        *p++ = entry->state_on ? 1 : 0;

        memcpy(p, &entry->random_start_count, 4);
        p += 4;
        for (auto& rs : entry->random_starts) {
            memcpy(p, &rs.elevation, 4);
            p += 4;
            memcpy(p, &rs.tile_num, 4);
            p += 4;
        }
    }

    return buf;
}

maps_txt_data* deserialize_maps_data(const uint8_t* buf, int size) {
    if (buf == nullptr || size < MAPS_DATA_SERIAL_SIZE) {
        printf("Warning: deserialize_maps_data(), buffer too small (%d < %d)\n", size,
               MAPS_DATA_SERIAL_SIZE);
        return nullptr;
    }

    maps_txt_data* data = (maps_txt_data*)calloc(1, sizeof(maps_txt_data));
    if (data == nullptr) {
        return nullptr;
    }

    const uint8_t* p = buf;

    memcpy(&data->map_count, p, 4);
    p += 4;

    data->map_count = std::min(data->map_count, MAX_MAP_ENTRIES);

    for (auto& m : data->maps) {
        map_entry* entry = &m;
        memcpy(&entry->map_number, p, 4);
        p += 4;
        memcpy(entry->lookup_name, p, MAP_NAME_LEN);
        p += MAP_NAME_LEN;
        entry->lookup_name[MAP_NAME_LEN - 1] = '\0';
        memcpy(entry->map_name, p, MAP_NAME_LEN);
        p += MAP_NAME_LEN;
        entry->map_name[MAP_NAME_LEN - 1] = '\0';
        memcpy(entry->music, p, MAP_NAME_LEN);
        p += MAP_NAME_LEN;
        entry->music[MAP_NAME_LEN - 1] = '\0';

        memcpy(&entry->ambient_sfx_count, p, 4);
        p += 4;
        entry->ambient_sfx_count = std::min(entry->ambient_sfx_count, MAX_AMBIENT_SFX);
        for (auto& sfx : entry->ambient_sfx) {
            memcpy(sfx.name, p, 32);
            p += 32;
            sfx.name[31] = '\0';
            memcpy(&sfx.weight, p, 4);
            p += 4;
        }

        entry->saved = (*p++ != 0);
        entry->dead_bodies_age = (*p++ != 0);
        entry->can_rest_here[0] = (*p++ != 0);
        entry->can_rest_here[1] = (*p++ != 0);
        entry->can_rest_here[2] = (*p++ != 0);
        entry->pipboy_active = (*p++ != 0);
        entry->state_on = (*p++ != 0);

        memcpy(&entry->random_start_count, p, 4);
        p += 4;
        entry->random_start_count = std::min(entry->random_start_count, MAX_RANDOM_STARTS);
        for (auto& rs : entry->random_starts) {
            memcpy(&rs.elevation, p, 4);
            p += 4;
            memcpy(&rs.tile_num, p, 4);
            p += 4;
        }
    }

    return data;
}
