#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

#include "Worldmap_Project.h"
#include "Image2Texture.h"
#include "display_FRM_OpenGL.h"
#include "ImGui_Warning.h"


bool write_worldmap_txt(const char* output_path, const char* base_name,
                        int tiles_x, int tiles_y, Surface* msk_srfc)
{
    char txt_path[MAX_PATH];
    snprintf(txt_path, MAX_PATH, "%s/worldmap.txt", output_path);

    FILE* file = fopen(txt_path, "w");
    if (!file) {
        printf("Error: write_worldmap_txt(), unable to open %s for writing: L%d\n", txt_path, __LINE__);
        return false;
    }

    // Lowercase copy of base_name for walk_mask_name to match vanilla convention.
    // MSK files are also saved lowercase by create_tile_name().
    char name_lower[8];
    int i = 0;
    for (; base_name[i] && i < 7; i++) {
        name_lower[i] = (char)tolower((unsigned char)base_name[i]);
    }
    name_lower[i] = '\0';

    int total_tiles = tiles_x * tiles_y;

    // --- [Data] ---
    fprintf(file, "; Generated by QFO2Tool\n");
    fprintf(file, "[Data]\n");
    fprintf(file, "Forced=100%%\n");
    fprintf(file, "Frequent=38%%\n");
    fprintf(file, "Common=22%%\n");
    fprintf(file, "Uncommon=12%%\n");
    fprintf(file, "Rare=4%%\n");
    fprintf(file, "None=0%%\n");
    fprintf(file, "terrain_types=Desert:1\n");
    fprintf(file, "terrain_short_names=DES\n\n");

    // --- [Random Maps: Desert] ---
    fprintf(file, "[Random Maps: Desert]\n");
    fprintf(file, "map_00=Desert Encounter 1\n\n");

    // --- Dummy encounter definition ---
    fprintf(file, "[Encounter: QFO2_Default]\n");
    fprintf(file, "type_00=Ratio:100%%, pid:16777221\n");
    fprintf(file, "position=Surrounding\n\n");

    // --- Encounter table ---
    fprintf(file, "[Encounter Table 0]\n");
    fprintf(file, "lookup_name=Default\n");
    fprintf(file, "maps=Desert Encounter 1\n");
    fprintf(file, "enc_00=Chance:0%%,Enc:(1) QFO2_Default\n\n");

    // --- [Tile Data] ---
    fprintf(file, "[Tile Data]\n");
    fprintf(file, "num_horizontal_tiles=%d\n\n", tiles_x);

    // --- [Tile N] sections ---
    int tile_num = 0;
    int full_w = msk_srfc ? msk_srfc->w : 0;
    for (int y = 0; y < tiles_y; y++)
    {
        for (int x = 0; x < tiles_x; x++)
        {
            fprintf(file, "[Tile %d]\n", tile_num);
            fprintf(file, "art_idx=%d\n", WRLDMP_ART_IDX + tile_num);
            fprintf(file, "encounter_difficulty=0\n");

            // Only emit walk_mask_name if this tile's mask has any non-zero pixels
            if (msk_srfc) {
                bool tile_has_data = false;
                for (int row = 0; row < WMAP_TILE_H && !tile_has_data; row++) {
                    int src_row = (y * WMAP_TILE_H + row) * full_w + x * WMAP_TILE_W;
                    for (int col = 0; col < WMAP_TILE_W; col++) {
                        if (msk_srfc->pxls[src_row + col]) {
                            tile_has_data = true;
                            break;
                        }
                    }
                }
                if (tile_has_data) {
                    fprintf(file, "walk_mask_name=%s%02d\n", name_lower, tile_num);
                }
            }

            // 7 columns x 6 rows = 42 subtile entries
            for (int sy = 0; sy < 7; sy++) {
                for (int sx = 0; sx < 6; sx++) {
                    fprintf(file, "%d_%d=Desert,No_Fill,None,None,None,Default\n", sy, sx);
                }
            }
            fprintf(file, "\n");
            tile_num++;
        }
    }

    fclose(file);
    printf("write_worldmap_txt(): wrote %d tiles to %s\n", total_tiles, txt_path);
    return true;
}


// Shared helper: set up OpenGL resources for a stitched worldmap surface.
// Takes ownership of nothing — caller still owns stitched and msk_srfc.
static bool init_wmap_opengl(Surface* stitched, Surface* msk_srfc,
                              LF* F_Prop, image_data* img_data,
                              shader_info* shaders)
{
    // allocate ANM_dir[6]
    img_data->ANM_dir = (ANM_Dir*)malloc(sizeof(ANM_Dir) * 6);
    if (!img_data->ANM_dir) {
        set_popup_warning(
            "[ERROR] init_wmap_opengl()\n\n"
            "Unable to allocate memory for ANM_dir."
        );
        printf("Error: init_wmap_opengl(), ANM_dir alloc failed : L%d\n", __LINE__);
        return false;
    }
    new (img_data->ANM_dir) ANM_Dir[6];

    // allocate frame_data[0]
    img_data->ANM_dir[0].frame_data = (Surface**)malloc(sizeof(Surface*));
    if (!img_data->ANM_dir[0].frame_data) {
        set_popup_warning(
            "[ERROR] init_wmap_opengl()\n\n"
            "Unable to allocate memory for frame_data."
        );
        printf("Error: init_wmap_opengl(), frame_data alloc failed : L%d\n", __LINE__);
        free(img_data->ANM_dir);
        img_data->ANM_dir = NULL;
        return false;
    }

    img_data->ANM_dir[0].frame_data[0] = stitched;
    img_data->ANM_dir[0].num_frames    = 1;
    img_data->width  = stitched->w;
    img_data->height = stitched->h;
    img_data->type   = FRM;
    img_data->display_orient_num = NE;
    img_data->display_frame_num  = 0;

    // allocate frame_box
    img_data->ANM_dir[0].frame_box = (rectangle*)calloc(1, sizeof(rectangle));
    if (!img_data->ANM_dir[0].frame_box) {
        set_popup_warning(
            "[ERROR] init_wmap_opengl()\n\n"
            "Unable to allocate memory for frame_box."
        );
        printf("Error: init_wmap_opengl(), frame_box alloc failed : L%d\n", __LINE__);
        free(img_data->ANM_dir[0].frame_data);
        free(img_data->ANM_dir);
        img_data->ANM_dir = NULL;
        return false;
    }

    // set bounding boxes
    img_data->ANM_dir[0].frame_box[0] = {0, 0, stitched->w, stitched->h};
    img_data->ANM_bounding_box[0]     = {0, 0, stitched->w, stitched->h};

    // create OpenGL texture + framebuffer
    img_data->FRM_texture = init_texture(
        stitched, stitched->w, stitched->h, FRM);

    framebuffer_init(
        &img_data->render_texture,
        &img_data->framebuffer,
        stitched->w,
        stitched->h);

    SURFACE_to_texture(
        stitched,
        img_data->FRM_texture,
        stitched->w, stitched->h, 1);

    draw_texture_to_framebuffer(
        shaders->FO_pal,
        shaders->render_FRM_shader,
        &shaders->giant_triangle,
        img_data->framebuffer,
        img_data->FRM_texture,
        stitched->w, stitched->h);

    // synthetic FRM_Header + FRM_Frame buffer so copy_it_all_ANM() works in edit mode
    int synth_size = sizeof(FRM_Header) + sizeof(FRM_Frame) + (stitched->w * stitched->h);
    uint8_t* synth_buf = (uint8_t*)calloc(1, synth_size);
    if (synth_buf) {
        FRM_Header* hdr    = (FRM_Header*)synth_buf;
        hdr->version           = 4;
        hdr->Frames_Per_Orient = 1;
        hdr->Frame_Area        = sizeof(FRM_Frame) + (stitched->w * stitched->h);

        FRM_Frame* frame   = (FRM_Frame*)(synth_buf + sizeof(FRM_Header));
        frame->Frame_Width  = stitched->w;
        frame->Frame_Height = stitched->h;
        frame->Frame_Size   = stitched->w * stitched->h;

        img_data->FRM_data = synth_buf;
        img_data->FRM_hdr  = hdr;
        img_data->FRM_size = synth_size;
    }

    // set up MSK texture if present
    if (msk_srfc) {
        img_data->MSK_srfc = msk_srfc;
        img_data->MSK_texture = init_texture(
            msk_srfc, msk_srfc->w, msk_srfc->h, MSK);
    }

    F_Prop->palettized        = true;
    F_Prop->file_open_window  = true;

    return true;
}


bool save_wmap_project(const char* path, LF* F_Prop)
{
    if (!F_Prop->wmap) {
        set_popup_warning(
            "[ERROR] save_wmap_project()\n\n"
            "No worldmap project data to save."
        );
        return false;
    }

    wmap_info* info = F_Prop->wmap;

    // Get pixel data: prefer edit_data if initialized, else img_data
    image_data* src_data = F_Prop->edit_data.ANM_dir ? &F_Prop->edit_data : &F_Prop->img_data;
    Surface* frm_srfc = src_data->ANM_dir[0].frame_data[0];
    Surface* msk_srfc = src_data->MSK_srfc;

    if (!frm_srfc || !frm_srfc->pxls) {
        set_popup_warning(
            "[ERROR] save_wmap_project()\n\n"
            "No FRM pixel data to save."
        );
        return false;
    }

    uint32_t frm_size = (uint32_t)(frm_srfc->w * frm_srfc->h);
    uint32_t msk_size = 0;
    bool has_msk = (info->has_msk && msk_srfc && msk_srfc->pxls);
    if (has_msk) {
        msk_size = (uint32_t)(msk_srfc->w * msk_srfc->h);
    }

    wmap_header hdr = {};
    memcpy(hdr.magic, "WMAP", 4);
    hdr.version    = 2;
    memset(hdr.base_name, 0, 8);
    strncpy(hdr.base_name, info->base_name, 7);
    hdr.tiles_x    = (uint32_t)info->tiles_x;
    hdr.tiles_y    = (uint32_t)info->tiles_y;
    hdr.flags      = has_msk ? 1 : 0;
    hdr.frm_offset = (uint32_t)sizeof(wmap_header);
    hdr.frm_size   = frm_size;
    hdr.msk_offset = has_msk ? (uint32_t)(sizeof(wmap_header) + frm_size) : 0;
    hdr.msk_size   = msk_size;

    FILE* fp = fopen(path, "wb");
    if (!fp) {
        set_popup_warning(
            "[ERROR] save_wmap_project()\n\n"
            "Unable to open file for writing."
        );
        printf("Error: save_wmap_project(), unable to open %s for writing: L%d\n", path, __LINE__);
        return false;
    }

    fwrite(&hdr, sizeof(wmap_header), 1, fp);
    fwrite(frm_srfc->pxls, frm_size, 1, fp);
    if (has_msk) {
        fwrite(msk_srfc->pxls, msk_size, 1, fp);
    }
    fclose(fp);

    // Update save_path
    strncpy(info->save_path, path, MAX_PATH - 1);
    info->save_path[MAX_PATH - 1] = '\0';

    printf("save_wmap_project(): wrote %s (%u + %u bytes)\n", path, frm_size, msk_size);
    return true;
}


bool load_wmap_project(const char* wmap_path, LF* F_Prop,
                       image_data* img_data, shader_info* shaders)
{
    FILE* fp = fopen(wmap_path, "rb");
    if (!fp) {
        set_popup_warning(
            "[ERROR] load_wmap_project()\n\n"
            "Unable to open .wmap file."
        );
        printf("Error: load_wmap_project(), Can't open file: %s : L%d\n", wmap_path, __LINE__);
        return false;
    }

    wmap_header hdr = {};
    if (fread(&hdr, sizeof(wmap_header), 1, fp) != 1) {
        set_popup_warning(
            "[ERROR] load_wmap_project()\n\n"
            "File too small for wmap header."
        );
        fclose(fp);
        return false;
    }

    // Validate magic
    if (memcmp(hdr.magic, "WMAP", 4) != 0) {
        set_popup_warning(
            "[ERROR] load_wmap_project()\n\n"
            "Not a valid .wmap binary file.\n"
            "(Missing WMAP magic header)"
        );
        fclose(fp);
        return false;
    }

    // Validate version
    if (hdr.version != 2) {
        set_popup_warning(
            "[ERROR] load_wmap_project()\n\n"
            "Unsupported .wmap version.\n"
            "Expected version 2."
        );
        fclose(fp);
        return false;
    }

    // Validate dimensions
    if (hdr.tiles_x < 1 || hdr.tiles_y < 1) {
        set_popup_warning(
            "[ERROR] load_wmap_project()\n\n"
            "Invalid tile dimensions in .wmap file."
        );
        fclose(fp);
        return false;
    }

    // Validate frm_size
    uint32_t expected_frm = hdr.tiles_x * WMAP_TILE_W * hdr.tiles_y * WMAP_TILE_H;
    if (hdr.frm_size != expected_frm) {
        set_popup_warning(
            "[ERROR] load_wmap_project()\n\n"
            "FRM data size does not match tile dimensions."
        );
        fclose(fp);
        return false;
    }

    int full_w = hdr.tiles_x * WMAP_TILE_W;
    int full_h = hdr.tiles_y * WMAP_TILE_H;

    // Read FRM pixel data
    Surface* stitched = Create_8Bit_Surface(full_w, full_h, shaders->FO_pal);
    if (!stitched) {
        set_popup_warning(
            "[ERROR] load_wmap_project()\n\n"
            "Unable to allocate FRM surface."
        );
        fclose(fp);
        return false;
    }

    fseek(fp, hdr.frm_offset, SEEK_SET);
    if (fread(stitched->pxls, hdr.frm_size, 1, fp) != 1) {
        set_popup_warning(
            "[ERROR] load_wmap_project()\n\n"
            "Failed to read FRM pixel data."
        );
        FreeSurface(stitched);
        fclose(fp);
        return false;
    }

    // Read MSK pixel data if present
    Surface* msk_full = NULL;
    bool has_msk = (hdr.flags & 1) && hdr.msk_offset > 0 && hdr.msk_size > 0;
    if (has_msk) {
        msk_full = Create_8Bit_Surface(full_w, full_h, nullptr);
        if (!msk_full) {
            set_popup_warning(
                "[ERROR] load_wmap_project()\n\n"
                "Unable to allocate MSK surface."
            );
            FreeSurface(stitched);
            fclose(fp);
            return false;
        }

        fseek(fp, hdr.msk_offset, SEEK_SET);
        if (fread(msk_full->pxls, hdr.msk_size, 1, fp) != 1) {
            set_popup_warning(
                "[ERROR] load_wmap_project()\n\n"
                "Failed to read MSK pixel data."
            );
            FreeSurface(msk_full);
            FreeSurface(stitched);
            fclose(fp);
            return false;
        }
    }

    fclose(fp);

    // Set up OpenGL resources
    if (!init_wmap_opengl(stitched, msk_full, F_Prop, img_data, shaders)) {
        FreeSurface(stitched);
        if (msk_full) FreeSurface(msk_full);
        return false;
    }

    // Allocate and populate wmap_info
    F_Prop->wmap = (wmap_info*)calloc(1, sizeof(wmap_info));
    if (!F_Prop->wmap) {
        set_popup_warning(
            "[ERROR] load_wmap_project()\n\n"
            "Unable to allocate wmap_info."
        );
        return false;
    }
    F_Prop->wmap->version = 2;
    memcpy(F_Prop->wmap->base_name, hdr.base_name, 8);
    F_Prop->wmap->tiles_x = (int)hdr.tiles_x;
    F_Prop->wmap->tiles_y = (int)hdr.tiles_y;
    F_Prop->wmap->has_msk = has_msk;
    strncpy(F_Prop->wmap->save_path, wmap_path, MAX_PATH - 1);
    F_Prop->wmap->save_path[MAX_PATH - 1] = '\0';

    return true;
}


bool new_wmap_project(LF* F_Prop, image_data* img_data, shader_info* shaders,
                      Surface* src, const char* base_name,
                      int tiles_x, int tiles_y)
{
    if (!src || !src->pxls) {
        set_popup_warning(
            "[ERROR] new_wmap_project()\n\n"
            "No source surface provided."
        );
        return false;
    }

    // Validate dimensions
    if (src->w % WMAP_TILE_W != 0 || src->h % WMAP_TILE_H != 0) {
        set_popup_warning(
            "[ERROR] new_wmap_project()\n\n"
            "Source image dimensions must be\n"
            "multiples of 350x300."
        );
        return false;
    }

    // Copy source surface (takes ownership of copy)
    Surface* stitched = Copy8BitSurface(src);
    if (!stitched) {
        set_popup_warning(
            "[ERROR] new_wmap_project()\n\n"
            "Unable to copy source surface."
        );
        return false;
    }

    // Set up OpenGL resources (no MSK for new projects)
    if (!init_wmap_opengl(stitched, NULL, F_Prop, img_data, shaders)) {
        FreeSurface(stitched);
        return false;
    }

    // Allocate and populate wmap_info
    F_Prop->wmap = (wmap_info*)calloc(1, sizeof(wmap_info));
    if (!F_Prop->wmap) {
        set_popup_warning(
            "[ERROR] new_wmap_project()\n\n"
            "Unable to allocate wmap_info."
        );
        return false;
    }
    F_Prop->wmap->version = 2;
    strncpy(F_Prop->wmap->base_name, base_name, 7);
    F_Prop->wmap->base_name[7] = '\0';
    F_Prop->wmap->tiles_x = tiles_x;
    F_Prop->wmap->tiles_y = tiles_y;
    F_Prop->wmap->has_msk = false;
    F_Prop->wmap->save_path[0] = '\0';

    return true;
}
